ALTER TABLE `characters` ADD COLUMN `avatar` varchar(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `doors` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`data` LONGTEXT NOT NULL,
	PRIMARY KEY (`id`)
);